### ISSUE TITLE
Outdated docker tag in v2.1.0 documentation

### ISSUE THREAD

**Issue by xtrcode** [tribe29/checkmk-docs#39]
In the docs for v2.1.0 the docker run example still uses 2.0.0-latest tag.

See: 
- de: https://github.com/tribe29/checkmk-docs/blame/2.1.0/de/introduction_docker.asciidoc#L62
- en: https://github.com/tribe29/checkmk-docs/blame/2.1.0/en/introduction_docker.asciidoc#L60

Is 2.0.0-latest still the recommended version or did just somebody forgot to update the docs?

**Comment by sebkir** [comment]
That should be 2.1.0, of course. Thanks for reporting this issue. I will fix it immediately.

**Comment by sebkir** [comment]
@xtrcode While updating the version, I also added another crucial piece of information when it comes to Checkmk 2.1.0 in a docker container. In order to be able to register the agent controller you have to publish the port of the REST API to the host.

That is what the second -p is there for.

Here is the commit:
0c9a55334cbea405cfb0b05816ca5c79dec76f81

The changes should be visible on the website tomorrow.

**Comment by sebkir** [comment]
Corrections are in place:

https://docs.checkmk.com/latest/en/introduction_docker.html
https://docs.checkmk.com/latest/de/introduction_docker.html
